name: "Build & Push Image - Github"
run-name: "Build & Push Image - <repo-name>:api-${{ github.event.inputs.tag }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: 'Image Target'
        default: dev
        required: true
        options:
        - prod
        - dev
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ACTIONS_DOCKER_USERNAME }}
          password: ${{ secrets.ACTIONS_DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: <repo-name>:api-${{ github.event.inputs.tag }}